services:
  - type: web
    name: defect-detection-backend
    runtime: docker
    plan: standard
    dockerfilePath: backend/Dockerfile
    envVars:
      - key: PORT
        value: 8000
    healthCheckPath: /health
    autoDeploy: true

  - type: web
    name: defect-detection-frontend
    env: static
    buildCommand: npm ci && npm run build
    staticPublishPath: frontend/dist
    rootDir: frontend
    routes:
      - type: rewrite
        source: "/*"
        destination: "/index.html"
    envVars:
      # Set this to the backend's public URL after the first deploy or via Render env group
      - key: VITE_API_BASE
        value: https://defect-detection-backend.onrender.com



